### ISSUE TITLE
'ViCareClimate' object has no attribute '_current_operation'

### ISSUE THREAD

**Issue by vandenberghev** [oischinger/ha_vicare#15]
'ViCareClimate' object has no attribute '_current_operation'

Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
connection.context(msg))
File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1138, in async_call
self._execute_service(handler, service_call))
File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1160, in _execute_service
await handler.func(service_call)
File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 188, in handle_service
self._platforms.values(), func, call, service_name
File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 314, in entity_service_call
future.result() # pop exception if have
File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 330, in _handle_service_platform_call
await func(entity, data)
File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/climate/init.py", line 564, in async_service_temperature_set
await entity.async_set_temperature(**kwargs)
File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/homeassistant/.homeassistant/custom_components/vicare/climate.py", line 216, in set_temperature
self._api.setProgramTemperature(self._current_operation, self._target_temperature)
AttributeError: 'ViCareClimate' object has no attribute '_current_operation'

**Comment by vandenberghev** [comment]
PR created for fix: https://github.com/oischinger/ha_vicare/pull/16

**Comment by vandenberghev** [comment]
P.S. Please don't manually copy/paste.
Accept PR's and respect the git history.

**Comment by oischinger** [comment]
@vandenberghev : Thanks for the PR. Sorry if I messed up with the merging process but in the end the git history might vanish anyway if we finally contribute to HA
