### ISSUE TITLE
Failure when CurrentPower is not provided by devices

### ISSUE THREAD

**Issue by cygnusb** [oischinger/ha_vicare#4]
I am getting a traceback on every query of my device (Vitodens 333)

Removing the current power from the list of  ViCareSensor fixes this issue. It would be good to have check if the attribute is present and ignore ViCareSensors, which are not present.

```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/sensor/vicare.py", line 79, in update
    api_method = getattr(ViCareSession, "get" + self.sensorName)
AttributeError: type object 'ViCareSession' has no attribute 'getCurrentPower'
```

**Comment by oischinger** [comment]
Closing old issue
