### ISSUE TITLE
config flow branch : Error setting up entry ViCare

### ISSUE THREAD

**Issue by Zixim** [oischinger/ha_vicare#49]
```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/vicare/__init__.py:118
Integration: Viessmann ViCare
First occurred: 8:42:21 AM (1 occurrences)
Last logged: 8:42:21 AM

Error setting up entry ViCare for vicare
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/vicare/__init__.py", line 105, in async_setup_entry
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vicare/__init__.py", line 118, in setup_vicare_api
    vicare_api.initWithCredentials(
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCare.py", line 24, in initWithCredentials
    self.initWithExternalOAuth(ViCareOAuthManager(
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCare.py", line 29, in initWithExternalOAuth
    self.__loadInstallations()
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCare.py", line 43, in __loadInstallations
    self.devices = list(self.__readInstallations(installations["data"]))
KeyError: 'data'

```

**Comment by Zixim** [comment]
hmm...I disabled/enabled the integration... seems normal now.
