### ISSUE TITLE
http connection failures are not catched

### ISSUE THREAD

**Issue by cygnusb** [oischinger/ha_vicare#5]
Failures in http connections result in exception tracebacks in home-assistant.log

Most possibly this should be catched and handled?

```
2019-02-03 11:02:02 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.vicare fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"

```

**Comment by oischinger** [comment]
I'm not quite sure what is the correct thing to do here.
PyViCare should handle exceptions arising from expiring tokens internally.
Sometimes however these exceptions are thrown and I have the feeling it's because of auth issues when I'm using the ViCare app in parallel.
We should report this stuff to the PyVicare project first. Closing this issue now.
