### ISSUE TITLE
Error while restarting homeassistant

### ISSUE THREAD

**Issue by b10126** [oischinger/ha_vicare#51]
Hi everyone,
I'm a great fan of this HA implementation! Does anyone know what I'm doing wrong? Everytime I restart HA I'll get this error message. After waiting one or two hours and the another restart it works fine. The update interval in the settings is 120sec.
Thanks a lot for your suggestions.
Benedikt

Logger: homeassistant.setup
Source: components/vicare/__init__.py:80
First occurred: 11:10:45 (1 occurrences)
Last logged: 11:10:45

Error during setup of component vicare
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fbbe50a5ac0>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.viessmann.com', port=443): Max retries exceeded with url: /iot/v1/equipment/installations?includeGateways=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbbe50a5ac0>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 255, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/vicare/__init__.py", line 80, in setup
    vicare_api = GazBoiler(conf[CONF_USERNAME], conf[CONF_PASSWORD], **params)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 60, in __init__
    self.service = ViCareCachedService(username, password, cacheDuration, client_id, token_file, circuit)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareCachedService.py", line 8, in __init__
    ViCareService.__init__(self, username, password, client_id, token_file, circuit)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareService.py", line 77, in __init__
    self._getInstallations()
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareService.py", line 269, in _getInstallations
    self.installations = self.__get(apiURLBase+"/equipment/installations?includeGateways=true")
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareService.py", line 201, in __get
    r=self.oauth.get(url).json()
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.viessmann.com', port=443): Max retries exceeded with url: /iot/v1/equipment/installations?includeGateways=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbbe50a5ac0>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by woehrl01** [comment]
Hi @b10126

The error which occures happens at `socket.getaddrinfo` a std library function. This mostly happens as the host can't be resolved. That usually happens if there is a DNS resolve error. I suggest checking this. If you run this inside docker, this is often a problem I receive myself. Recreating the docker network usually resolved this on my side.

**Comment by b10126** [comment]
Oh thats a good hint! I'll try this one out, maybe it is really due to network connection issues. HA runs inside docker in my config.
Thanks a lot.
My first thought was about that Viessmann blocks access, due to max tries, but the error didn't return periodically / didn't make sense the way it occurred....

**Comment by oischinger** [comment]
Hey @b10126  I'll close this issue. please let me know if there's something we should check on the vicare integration side

**Comment by b10126** [comment]
Many thanks!
