### ISSUE TITLE
Exception: I/O in event loop

### ISSUE THREAD

**Issue by oischinger** [oischinger/ha_vicare#59]
```
Logger: homeassistant.components.sensor
Source: util/async_.py:140
Integration: Sensor (documentation, issues)
First occurred: 08:45:51 (1 occurrences)
Last logged: 08:45:51

Error while setting up vicare platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/vicare/sensor.py", line 300, in async_setup_entry
    entity = _build_entity(
  File "/config/custom_components/vicare/sensor.py", line 277, in _build_entity
    sensor.value_getter(vicare_api)
  File "/config/custom_components/vicare/sensor.py", line 80, in <lambda>
    value_getter=lambda api: api.getOutsideTemperature(),
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 45, in feature_flag_wrapper
    return wrapper(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 51, in getOutsideTemperature
    return self.service.getProperty("heating.sensors.temperature.outside")["properties"]["value"]["value"]
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareCachedService.py", line 24, in getProperty
    data = self.__get_or_update_cache()
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareCachedService.py", line 36, in __get_or_update_cache
    data = self.fetch_all_features()
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareService.py", line 56, in fetch_all_features
    return self.oauth_manager.get(url)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareAbstractOAuthManager.py", line 37, in get
    response = self.__oauth.get(f"{API_BASE_URL}{url}").json()
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1290, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 219, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 140, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/vicare/sensor.py, line 80: value_getter=lambda api: api.getOutsideTemperature(),
```

**Comment by oischinger** [comment]
@woehrl01 I wonder if we should either fix this locally in Home Assistant in async_setup_entry.
I would also love to migrate from `update` to `async_update` which would require us to do no I/O in that method. Meaning:
PyVicare would require a bit of refactoring again to do I/O only when manually triggered, e.g. by an updateCache() function.
The getters would always have to return cached values in that case.

Is this a direction that we should go?

**Comment by oischinger** [comment]
resolved some time ago
