### ISSUE TITLE
Update for climate.vitocal_heating fails

### ISSUE THREAD

**Issue by h4nnes** [oischinger/ha_vicare#98]
Hi,
I get a lot of errors in the log (see below). 

Any solution for this?
Thanks!

 File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vicare/climate.py", line 236, in update
    self._attributes["vicare_programs"] = self._circuit.getPrograms()
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 45, in feature_flag_wrapper
    return wrapper(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 500, in getPrograms
    return self.service.getProperty(f"heating.circuits.{self.circuit}.operating.programs")["components"]
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareCachedService.py", line 26, in getProperty
    return readFeature(entities, property_name)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareService.py", line 17, in readFeature
    raise PyViCareNotSupportedFeatureError(property_name)
PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: heating.circuits.0.operating.programs
2022-05-17 15:49:10 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.vitocal_heating fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vicare/climate.py", line 236, in update
    self._attributes["vicare_programs"] = self._circuit.getPrograms()
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 45, in feature_flag_wrapper
    return wrapper(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 500, in getPrograms
    return self.service.getProperty(f"heating.circuits.{self.circuit}.operating.programs")["components"]
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareCachedService.py", line 26, in getProperty
    return readFeature(entities, property_name)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareService.py", line 17, in readFeature
    raise PyViCareNotSupportedFeatureError(property_name)
PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: heating.circuits.0.operating.programs
2022-05-17 15:50:09 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.vitocal_heating fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vicare/climate.py", line 236, in update
    self._attributes["vicare_programs"] = self._circuit.getPrograms()
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 45, in feature_flag_wrapper
    return wrapper(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 500, in getPrograms
    return self.service.getProperty(f"heating.circuits.{self.circuit}.operating.programs")["components"]
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareCachedService.py", line 26, in getProperty
    return readFeature(entities, property_name)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareService.py", line 17, in readFeature
    raise PyViCareNotSupportedFeatureError(property_name)
PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: heating.circuits.0.operating.programs
2022-05-17 15:51:09 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.vitocal_heating fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vicare/climate.py", line 236, in update
    self._attributes["vicare_programs"] = self._circuit.getPrograms()
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 45, in feature_flag_wrapper
    return wrapper(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 500, in getPrograms
    return self.service.getProperty(f"heating.circuits.{self.circuit}.operating.programs")["components"]
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareCachedService.py", line 26, in getProperty
    return readFeature(entities, property_name)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareService.py", line 17, in readFeature
    raise PyViCareNotSupportedFeatureError(property_name)
PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: heating.circuits.0.operating.programs
2022-05-17 15:52:10 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.vitocal_heating fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vicare/climate.py", line 236, in update
    self._attributes["vicare_programs"] = self._circuit.getPrograms()
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 45, in feature_flag_wrapper
    return wrapper(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 500, in getPrograms
    return self.service.getProperty(f"heating.circuits.{self.circuit}.operating.programs")["components"]
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareCachedService.py", line 26, in getProperty
    return readFeature(entities, property_name)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareService.py", line 17, in readFeature
    raise PyViCareNotSupportedFeatureError(property_name)
PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: heating.circuits.0.operating.programs

**Comment by oischinger** [comment]
Fixed with at least 1.0.0-beta1
